main: me.CloverCola.HotPotato.HotPotatoMain
name: HotPotato
version: 0.5
api-version: 1.16
author: CloverCola

commands:
  hotpotato:
    description: Basic command for Hot Potato. Do "/hotpotato" for help.